# Generated by Django 6.0.3 on 2026-03-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=60),
        ),
    ]
