# Generated by Django 6.0.3 on 2026-05-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_servico_alter_agendamento_unique_together_and_more'),
        ('agendamento', '0003_create_superuser'),
    ]

    operations = [
    ]
