# Generated by Django 6.0.3 on 2026-04-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_servico_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=10),
        ),
    ]
