# Generated by Django 6.0.4 on 2026-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('bloqueio', 'Bloqueio'), ('liberado', 'Liberado')], max_length=10)),
            ],
            options={
                'unique_together': {('data', 'horario', 'tipo')},
            },
        ),
    ]
