# Generated by Django 6.0.3 on 2026-04-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_horariobloqueado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariobloqueado',
            unique_together={('data', 'horario')},
        ),
    ]
