# Generated by Django 6.0.3 on 2026-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_alter_horariobloqueado_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
